#! /bin/sh
# vim: foldmethod=marker foldlevel=0


# Usage Message {{{

USAGE="
SYNOPSYS
    ${0##*/} [options] [files...]

DESCRIPTION
    Edit a list of filenames in your \$EDITOR (default=vim) to be moved.
    If no files are given, use all files present in the current directory.

OPTIONS
    -h, --help
        Displays this usage information and exits

    -c, --copy
        Copies files, instead of moving them

    -d --dotfiles
        Do not ignore files prefixed with a '.'

    -t --time
        Sort files by time of creation; newest first

    -D --dirs-first
        Show directories before file entries

NOTE
    If the names of your files conflict with those of the flags, put them
    after a double dash (--), like this:
        ${0##*/} -- --copy
    This will rename a file called '--copy', instead of activating the
    '--copy' switch.
"

# }}}

fatal() {
    >&2 echo "$@"
    exit 1
}


g_opt_cmd="mv"
g_opt_log=0
g_opt_dotfiles=0
g_opt_sort_by_time=0
g_opt_dirs_first=0


# getopt argument parsing {{{
args="$(getopt -o "hcldtD" -l "help,copy,log,dotfiles,time,dirs-first" -n "${0##*/}" -- "$@")" \
    || fatal "Error parsing arguments!"
eval set -- "$args"

while true; do
    case "$1" in
        --) shift; break ;;
        -h|--help)
            >&2 echo "$USAGE"
            exit 0
            ;;
        -c|--copy)
            g_opt_cmd="cp"
            shift
            ;;
        -l|--log)
            g_opt_log=1
            shift
            ;;
        -d|--dotfiles)
            g_opt_dotfiles=1
            shift
            ;;
        -t|--time)
            g_opt_sort_by_time=1
            shift
            ;;
        -D|--dirs-first)
            g_opt_dirs_first=1
            shift
            ;;
    esac
done
# }}}


src_files="$(mktemp bmv-src.XXXXXXXXXX --tmpdir)"
ls_flags=""
[ "$g_opt_dotfiles" = 1 ]     && ls_flags="$ls_flags --all"
[ "$g_opt_sort_by_time" = 1 ] && ls_flags="$ls_flags -t"
[ "$g_opt_dirs_first" = 1 ]   && ls_flags="$ls_flags --group-directories-first"


# Read names from stdin, each one a line, if anything is piped
if ! [ -t 0 ]; then
    cat >> "$src_files"
else
    if [ $# -eq 0 ]; then
        # Maybe this 'ls' should be 'find'
        # shellcheck disable=SC2086
        ls $ls_flags >> "$src_files"
    else
        printf "%s\n" "$@" >> "$src_files"
    fi
fi


dst_files="$(mktemp bmv-dst.XXXXXXXXXX --tmpdir)"
echo "# Rename your files, save and quit" >> "$dst_files"
cat "$src_files" >> "$dst_files"

</dev/tty "${EDITOR:-vim}" "$dst_files"
sed -Ei '/^[[:space:]]*#/d' "$dst_files"

[ "$(wc -l < "$src_files")" -ne "$(wc -l < "$dst_files")" ] \
    && fatal "Unmatching ammount of names. Exiting."


cmd_list="$(mktemp bmv-cmd.XXXXXXXXXX --tmpdir)"
echo "# The following commands will be executed" >> "$cmd_list"

parallel --keep-order --link --trim lr \
        echo "$g_opt_cmd" -vi '{= if ($arg[1] ne $arg[2]) {$_=Q($_)} else {skip} =}' \
        :::: "$src_files" "$dst_files" \
    >> "$cmd_list"

rm "$src_files" "$dst_files"
[ "$(wc -l < "$cmd_list")" -lt 2 ] && fatal "No name changed. Exiting."

</dev/tty "${EDITOR:-vim}" "$cmd_list"
sed -Ei '/^[[:space:]]*#/d' "$cmd_list"

if [ "$g_opt_log" = "1" ]; then
   cp "$cmd_list" bmv.log
   echo "Logged 'cmd_list' to 'bmv.log'"
fi

. "$cmd_list"
rm "$cmd_list"

