#! /usr/bin/env python


import sqlite3
import sys
import os


CMD = "SELECT action_url, username_value, password_value FROM logins"

PATH = {
    "linux": os.path.expanduser("~/.config/chromium/Default/Login Data"),
    "win32": os.environ.get("LOCALAPPDATA", "") + r"\Google\Chrome\User Data\Default\Login Data",
    "darwin": os.path.expanduser("~/Library/Application Support/Google/Chrome/Default/Login Data"),
}


def iter_data():

    filter_user = lambda url, user, pw: user
    connection = sqlite3.connect(PATH[sys.platform])
    data = filter(filter_user, connection.execute(CMD).fetchall())

    if sys.platform == "win32":
        from win32crypt import CryptUnprotectData
        data = ((url, user, CryptUnprotectData(pw)[1]) for url, user, pw in data)

    yield from data


def main():
    print("Website, Username, Password:", file=sys.stderr)
    print("\n".join(f'"{w}", "{u}", "{p}"' for w, u, p in iter_data()))


if __name__ == "__main__":
    main()

