#! /usr/bin/env python3

"""Copy 'markdown' text from stdin, to the clipboard, as html, for pasting in word processors"""

import sys
import subprocess as sp
import textwrap


def main() -> int:
    lines = textwrap.dedent(sys.stdin.read())

    pandoc_out = sp.run(["pandoc", "--from", "markdown", "--to", "html"],
            input=lines, text=True, check=True, capture_output=True)
    sp.run(["xclip", "-i", "-t", "text/html", "-selection", "clipboard"],
            input=pandoc_out.stdout,
            text=True, check=True, capture_output=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

