#! /usr/bin/env python3

import sys
import subprocess as sp


def main() -> int:
    min_leading_spaces = float("inf")
    lines = []
    for line in sys.stdin:
        leading_spaces = 0
        for char in line:
            if char == ' ':
                leading_spaces +=1
            elif char == '\t':
                leading_spaces +=4
            else:
                break
        if leading_spaces < min_leading_spaces:
            min_leading_spaces = leading_spaces
        lines.append(line)
    if not len(lines):
        return 1
    if min_leading_spaces > 0:
        lines = [line[min_leading_spaces:] for line in lines]

    pandoc_out = sp.run(["pandoc", "--from", "markdown", "--to", "html"],
            input="".join(lines),
            text=True, check=True, capture_output=True)
    sp.run(["xclip", "-i", "-t", "text/html", "-selection", "clipboard"],
            input=pandoc_out.stdout,
            text=True, check=True, capture_output=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

