#! /usr/bin/env sh


cd "$HOME/Dotfiles/general"

for prog in "$@"; do
    case "$prog" in
        i3)
            cp -rf .config/i3/ "$XDG_CONFIG_HOME"
            echo "Updated i3wm config"
            ;;
        i3laptop)
            cp -rf .config/i3/ "$XDG_CONFIG_HOME"
            patch "$XDG_CONFIG_HOME/i3/config" .config/i3/laptop.diff
            echo "Updated i3wm laptop config"
            ;;
        laptopdiff)
            diff -u .config/i3/config  "$XDG_CONFIG_HOME/i3/config" > .config/i3/laptop.diff
            echo "Updated i3wm laptop.diff"
            ;;
        vim)
            cp -rf .vim "$HOME"
            echo "Updated vim."
            ;;
        rofi)
            cp -rf .config/rofi "$XDG_CONFIG_HOME"
            echo "Updated rofi config"
            ;;
        fish)
            cp -rf .config/fish "$XDG_CONFIG_HOME"
            echo "Updated fish config"
            ;;
        bash)
            cp .bashrc "$HOME"
            echo "Updated bashrc."
            ;;
        polybar)
            cp -rf .config/polybar "$XDG_CONFIG_HOME"
            echo "Updated polybar config"
            ;;
        profile)
            cp .profile "$HOME"
            echo "Updated profile."
            ;;
        -h)
            echo "i3 rofi fish bash polybar"
            ;;
        *)
            echo "Unknow option $prog. run dotupdate -l to list valid args"
            ;;
    esac
done

