#! /usr/bin/env sh


[ -d "$DOTFILES" ] || { >&2 echo '"Aborting.' && exit 1; }


cd "$DOTFILES/general"


for prog in "$@"; do
    case "$prog" in
        i3)
            cp -rf .config/i3/ "$XDG_CONFIG_HOME"
            i3-msg command restart
            echo "Updated i3wm config"
            ;;
        vim)
            cp -rf .config/vim "$XDG_CONFIG_HOME"
            echo "Updated vim."
            ;;
        rofi)
            cp -rf .config/rofi "$XDG_CONFIG_HOME"
            echo "Updated rofi config"
            ;;
        fish)
            cp -rf .config/fish "$XDG_CONFIG_HOME"
            echo "Updated fish config"
            ;;
        bash)
            cp .bashrc "$HOME"
            echo "Updated bashrc."
            ;;
        polybar)
            cp -rf .config/polybar "$XDG_CONFIG_HOME"
            polybar-msg cmd restart
            echo "Updated polybar config"
            ;;
        profile)
            cp -f .profile "$HOME"
            echo "Updated profile."
            ;;
        sxiv)
            cp -rf .config/sxiv  "$XDG_CONFIG_HOME"
            echo "Updated sxiv."
            ;;
        qutebrowser)
            cp -rf .config/qutebrowser "$XDG_CONFIG_HOME"
            cp -rf .local/share/qutebrowser "$XDG_DATA_HOME"
            echo "Updated qutebrowser."
            ;;
        sxhkd)
            cp -rf .config/sxhkd "$XDG_CONFIG_HOME"
            
            if sxhkd_pid="$(pidof sxhkd)"; then
                kill -9 "$sxhkd_pid"
                sxhkd &
            fi

            echo "Updated sxhkd."
            ;;
        aliases)
            cp -rf .config/aliases.sh "$XDG_CONFIG_HOME"
            echo "Updated aliases.sh"
            ;;
        -h)
            echo "i3 rofi fish bash polybar sxiv profile i3laptop laptopdiff sxhkd"
            ;;
        *)
            echo "Unknow option $prog. run dotupdate -h to list valid args"
            ;;
    esac
done

