#! /usr/bin/env python3
# vim: foldmethod=marker foldlevel=0

import argparse as ap
import logging
import os
from pathlib import Path
import re
import typing

if typing.TYPE_CHECKING:
    from collections.abc import Callable
    from typing import Any, Final

_make_shell_completions: Callable[[ap.ArgumentParser], Any]
try:
    import argcomplete
    _make_shell_completions = argcomplete.autocomplete
except ImportError as error:
    logging.info("Won't be able to generate shell completions as optional dependency '%s' missing.", error.name)
    _make_shell_completions = lambda x: x # noqa


HISTORYFILE_CMDENTRY_PATTERN: Final = re.compile(r'^-\s*cmd\s*:\s*')


def clamp[N: (int, float)](value: N, low: N, high: N) -> N:
    return min(max(low, value), high)


def get_cli_args() -> ap.Namespace:
    parser = ap.ArgumentParser()
    parser.add_argument("-f", "--history_file", default=None, type=Path, help="it's usually $HOME/.local/share/fish/fish_history")
    parser.add_argument("-v", "--verbose", action="count", default=0)
    _make_shell_completions(parser)

    return parser.parse_args()


def resolve_historyfile_path() -> Path:
    basename = os.environ.get("fish_history", "fish_history")
    if basename == "":
        error = RuntimeError("Keeping of history data is disabled for this fish session.")
        error.add_note('$fish_history was exported as ""')
        error.add_note("See fish's docs for the meaning of a set-to-empty $fish_history")
        raise error
    try:
        p = os.path.join(os.environ["XDG_DATA_HOME"], "fish", basename)
    except KeyError:
        p = os.path.join(os.environ["HOME"], ".local", "share", "fish", basename)
    return Path(p)


def _main_impl(
    history_file: Path | None,
    verbose: int
) -> int:
    logging.basicConfig(level=[logging.WARNING, logging.INFO, logging.DEBUG][clamp(verbose, 0, 2)])
    history_file = history_file or resolve_historyfile_path()

    current_block = []
    blocks = [current_block]
    with open(history_file) as src:
        for line in src:
            if not line:
                continue
            if line.startswith("- "):
                blocks.append(current_block := [])
                current_block.append(line)
            elif line.isspace():
                continue
            else:
                current_block.append(line)
    logging.info("%s: found %d total history entries", history_file, len(blocks))

    blocks_to_delete = []
    seen_cmds = set()
    for i, block in enumerate(reversed(blocks)):
        for line in block:
            if (result := HISTORYFILE_CMDENTRY_PATTERN.match(line)) is None:
                continue
            if (cmd := line[result.end():]) not in seen_cmds:
                seen_cmds.add(cmd)
            else:
                blocks_to_delete.append(len(blocks)-1 - i)
    duplicate_block_count = len(blocks_to_delete)
    logging.info("%s: found %d duplicate history entries", history_file, duplicate_block_count)

    written_blocks = 0
    with open(history_file, "w") as dst:
        for i, block in enumerate(blocks):
            if len(blocks_to_delete) != 0 and blocks_to_delete[-1] == i:
                blocks_to_delete.pop()
                continue
            dst.write("".join(block))
            written_blocks += 1
    logging.info("%s: wrote %d history entries", history_file, written_blocks)
    assert len(blocks) - duplicate_block_count == written_blocks

    return 0


def main() -> None:
    raise SystemExit(_main_impl(**vars(get_cli_args())))


if __name__ == "__main__":
    main()
