#! /bin/sh


notify-error() {
    notify-send \
        --expire-time=5000 \
        --icon=dialog-error \
        --urgency=NORMAL \
        "$1" "$2"
}


notify-launch() {
    notify-send \
        --expire-time=5000 \
        --icon=preferences-desktop-launch-feedback \
        --urgency=NORMAL \
        "$1" "$2"
}


if ! which "$1" >/dev/null 2>&1; then
    notify-error "'detach' util not found!" "Please install 'detach from the AUR'"
    exit 1
elif ! which "$1" >/dev/null 2>&1; then
    notify-error "Error opening '$1'" "No '$1' in <i>\$PATH</i>"
    exit 1
else
    notify-launch "Launching '$1'"
    detach "$@"
    exit 0
fi

