#! /bin/sh


notify_error() {
    notify-send \
        --expire-time=5000 \
        --icon=dialog-error \
        --urgency=NORMAL \
        "$1" "$2"
}


notify_launch() {
    notify-send \
        --expire-time=5000 \
        --icon=preferences-desktop-launch-feedback \
        --urgency=NORMAL \
        "$1" "$2"
}


if ! which "$1" >/dev/null 2>&1; then
    notify_error "Error opening '$1'" "No '$1' in <i>\$PATH</i>"
    exit 1
else
    notify_launch "Launching '$1'"
    exec "$@" &
fi

