#! /bin/sh


ICON_DL="/usr/share/icons/Papirus/32x32/apps/downloader-arrow.svg"
ICON_ERR="/usr/share/icons/Papirus/32x32/status/dialog-error.svg"


cd "$XDG_VIDEOS_DIR" || >&2 echo '$XDG_VIDEOS_DIR not defined.' && exit 1


url=$(xsel -ob)

if [ -z "$url" ]; then
    notify-send "Couldn't download video" "Clipboard is empty" -t 5000 -i "$ICON_ERR"
    exit 1
fi

notify-send "Commencing video download." "URL: \"$url\"" -t 5000 -i "$ICON_DL"


if ! yt-dlp "$url"; then
    notify-send "Error on download!" -t 5000 -i "$ICON_ERR"
    exit 1
fi

notify-send "Download has finished!" -t 5000

