#! /bin/sh


ICON_DL="/usr/share/icons/Papirus/32x32/apps/downloader-arrow.svg"
ICON_ERR="/usr/share/icons/Papirus/32x32/status/dialog-error.svg"
ICON_DONE=""


cd "$HOME"/Videos

url=$(xclip -selection clipboard -o)

notify-send "Commencing video download." "$url" -t 5000 -i "$ICON_DL"
youtube-dl "$url"

if [ $? == 0 ]; then
    notify-send "Download has finished!" -t 5000
else
    notify-send "Error on download!" -t 5000 -i "$ICON_ERR"
fi
