#! /bin/sh
# Interactive Dotfile UPdater

# This is irrelevant because even Dash implements 'local'
# shellcheck disable=SC3043

readonly DOTS_CFG_ROOT="${DOTFILES:-$HOME/dots}/home/.config"
readonly HOME_CFG_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}"
readonly CR="$(printf '\r')"


escape_quotes() {
    # {{{
    printf "'%s'" "$(printf '%s' "$1" | sed "s|'|'\\\\''|g")"
} # }}}


# <Esc> control sequences
readonly _cs_begin="$(printf '\033[')" # ESC + [
readonly _cs_end=m
readonly _cs_reset=0
readonly _cs_bold=1
readonly _cs_yellow=33


# (escape_seq: str, words: str)
_paint_word() {
    printf "${_cs_begin}%s${_cs_end}%s${_cs_begin}${_cs_reset}${_cs_end}" "$1" "$2"
}


# (msg: str, valid_chars: str, default_val: str)
_prompt_choice() {
    local msg="$1"
    local valid_chars="$2"
    local default_val="$3"

    while true; do
        >&2 printf \
            "%s (one of '%s' [defaults to '%s']):\r\n" \
            "$msg" "$valid_chars" "$default_val"

        local response
        response=$(head -c 1)

        if [ "$response" = "$CR" ]; then
            echo "$default_val"
            return
        fi

        if echo "$valid_chars" | grep --quiet "$response"; then
            echo "$response"
            return
        fi
        >&2 printf "Invalid response: '%s'. Try again.\r\n" "$response"
    done
}


# (msg: str, valid_chars: str, default_val: str)
prompt_choice() {
    local msg="$1"
    local valid_chars="$2"
    local default_val="$3"

    local old_stty_cfg
    old_stty_cfg=$(stty -g)
    stty raw -echo isig

    local ret
    ret="$(_prompt_choice "$msg" "$valid_chars" "$default_val")"

    stty "$old_stty_cfg"
    echo "$ret"
}


# (src_root: str, dst_root: str, dirname: str)
sync_dir() {
    local src="$1"
    local dst="$2"
    IFS="
    "

    # First we sync the subfolders in these directories
    # {{{
    local f_src_children="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$src" -maxdepth 1 -type d -printf '%P\n' | sort > "$f_src_children"

    local f_dst_children="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$dst" -maxdepth 1 -type d -printf '%P\n' | sort > "$f_dst_children"

    for only_in_src in $(comm -23 "$f_src_children" "$f_dst_children"); do
        # {{{
        >&2 printf "Subdirectory %s is missing in DST (%s)\n" \
            "$(_paint_word "$_cs_bold;$_cs_yellow" "$(escape_quotes "$only_in_src")")" \
            "$(escape_quotes "$dst")"

        case "$(prompt_choice "Peek into this directory?" "yn" "n")" in
            y*) ls "${src:?}/$only_in_src" | "${PAGER:-less}";;
            *) ;;
        esac

        case "$(prompt_choice "[C]reate | [I]gnore | [R]emove" "cir" "i")" in
            c*) mkdir "$dst/$only_in_src"; sync_dir "$src/$only_in_src" "$dst/$only_in_src" ;;
            r*) rm -rf "${src:?}/$only_in_src" ;;
            i*) ;;
            *) >&2 echo "Got invalid response" ;;
        esac

        printf '\n'
    done # }}}

    for only_in_dst in $(comm -13 "$f_src_children" "$f_dst_children"); do
        # {{{
        >&2 printf "Subdirectory %s is missing in SRC (%s)\n" \
            "$(_paint_word "$_cs_bold;$_cs_yellow" "$(escape_quotes "$only_in_dst")")" \
            "$(escape_quotes "$src")"

        case "$(prompt_choice "Peek into this directory?" "yn" "n")" in
            y*) ls "${dst:?}/$only_in_dst" | "${PAGER:-less}";;
            *) ;;
        esac

        case "$(prompt_choice "[C]reate | [I]gnore | [R]emove" "cir" "i")" in
            c*) mkdir "${src:?}/$only_in_dst"; sync_dir "$src/$only_in_dst" "$dst/$only_in_dst" ;;
            r*) rm -rf "${dst:?}/$only_in_dst" ;;
            i*) ;;
            *) >&2 echo "Got invalid response" ;;
        esac

        printf '\n'
    done # }}}

    for common_dir in $(comm -12 "$f_src_children" "$f_dst_children"); do
        sync_dir "$src/$common_dir" "$dst/$common_dir"
    done

    rm "$f_src_children" "$f_dst_children"
    # }}}

    # And then we sync the file contents of the same directories
    # {{{
    local f_files_in_src="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$src" -maxdepth 1 -type f -printf '%P\n' | sort > "$f_files_in_src"

    local f_files_in_dst="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$dst" -maxdepth 1 -type f -printf '%P\n' | sort > "$f_files_in_dst"

    if [ -r "$dst/.idup_ignore" ]; then
        local f_files_in_dst_after_idup_ignore="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"

        while IFS= read -r file_in_dst; do
            local matched=0
            while IFS= read -r glob_to_ignore; do
                case $file_in_dst in
                    $glob_to_ignore) matched=1; break ;;
                esac
            done < "$dst/.idup_ignore"
            [ "$matched" -eq 0 ] && printf '%s\n' "$file_in_dst" >> "$f_files_in_dst_after_idup_ignore"
        done < "$f_files_in_dst"

        mv "$f_files_in_dst_after_idup_ignore" "$f_files_in_dst"
    fi

    for only_in_src in $(comm -23 "$f_files_in_src" "$f_files_in_dst"); do
        # {{{
        >&2 printf "File %s only exists in SRC (%s)\n" \
            "$(_paint_word "$_cs_bold;$_cs_yellow" "$(escape_quotes "$only_in_src")")" \
            "$(escape_quotes "$src")"

        case "$(prompt_choice "Peek into the file?" "yn" "n")" in
            y*) "${PAGER:-less}" "${src:?}/$only_in_src";;
            *) ;;
        esac

        case "$(prompt_choice "[C]opy from repo | [I]gnore | [R]emove from repo" "cir" "i")" in
            c*) cp "${src:?}/$only_in_src" "$dst" ;;
            i*) ;;
            r*) >&2 git rm "${src#$DOTS_CFG_ROOT/}/$only_in_src" ;;
            *) >&2 echo "Got invalid response" ;;
        esac

        printf '\n'
    done # }}}

    for only_in_dst in $(comm -13 "$f_files_in_src" "$f_files_in_dst"); do
        # {{{
        >&2 printf "File %s only exists in DST (%s)\n" \
            "$(_paint_word "$_cs_bold;$_cs_yellow" "$(escape_quotes "$only_in_dst")")" \
            "$(escape_quotes "$dst")"

        case "$(prompt_choice "Peek into the file?" "yn" "n")" in
            y*) "${PAGER:-less}" "${dst:?}/$only_in_dst";;
            *) ;;
        esac

        case "$(prompt_choice "[C]opy into repo | [D]elete | [I]gnore" "cdi" "i")" in
            c*) cp "$dst/$only_in_dst" "$src"; >&2 git add "$src/$only_in_dst" ;;
            d*) rm "$dst/$only_in_dst";;
            i*) ;;
            *) >&2 echo "Got invalid response" ;;
        esac

        printf '\n'
    done # }}}

    for common_file in $(comm -12 "$f_files_in_src" "$f_files_in_dst"); do
        # {{{

        if diff --brief "$src/$common_file" "$dst/$common_file" >/dev/null 2>&1; then
            continue
        fi

        >&2 printf "Different versions of %s exist in SRC (%s) and DST (%s)\n" \
            "$(_paint_word "$_cs_bold;$_cs_yellow" "$(escape_quotes "$common_file")")" \
            "$(escape_quotes "$src")" \
            "$(escape_quotes "$dst")"

        case "$(prompt_choice "Peek into files? (Remote/Local/Diff/None)" "rldn" "n")" in
            r*) "${PAGER:-less}" "$src/$common_file";;
            l*) "${PAGER:-less}" "$dst/$common_file";;
            d*)
                # diff --color=always "$src/$common_file" "$dst/$common_file" | "${PAGER:-less -r}"
                vimdiff "$src/$common_file" "$dst/$common_file"
                case "$(prompt_choice "Edit files? (Remote/Local/None)" "rln" "n")" in
                    r*) "${EDITOR:-vim}" "$src/$common_file" ;;
                    l*) "${EDITOR:-vim}" "$dst/$common_file" ;;
                    n*) ;;
                esac
                ;;
            *) ;;
        esac

        case "$(prompt_choice "[R]estore from repo | [P]ush local to repo | [I]gnore" "rpi" "i")" in
            r*) cp "$src/$common_file" "$dst";;
            p*) cp "$dst/$common_file" "$src" && >&2 git add "$src/$common_file" ;;
            i*) ;;
            *) >&2 echo "Got invalid response" ;;
        esac

        printf '\n'
    done # }}}

    rm "$f_files_in_src" "$f_files_in_dst"
    # }}}
}


main_cli() {
    cd "$DOTS_CFG_ROOT" || exit 1
    for dir_to_sync; do
        local src="$DOTS_CFG_ROOT/$dir_to_sync"
        local dst="$HOME_CFG_ROOT/$dir_to_sync"

        if ! [ -d "$src" ]; then
            >&2 echo "'$dir_to_sync' doesn't exist in SRC ('$src'). Skipping"
            continue
        fi
        if ! [ -d "$dst" ]; then
            >&2 echo "'$dir_to_sync' doesn't exist in DST ('$dst'). Skipping"
            continue
        fi

        sync_dir "$DOTS_CFG_ROOT/$dir_to_sync" "$HOME_CFG_ROOT/$dir_to_sync"
    done
}


main_fzf() {
    local f_src_dirs="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$DOTS_CFG_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sort > "$f_src_dirs"
    local f_dst_dirs="$(mktemp "cfgdiff.XXXXXXXXXX" --tmpdir)"
    find "$HOME_CFG_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sort > "$f_dst_dirs"

    local dirs_to_sync="$(comm -12 "$f_src_dirs" "$f_dst_dirs" | fzf -i -m)"
    rm "$f_src_dirs" "$f_dst_dirs"
    cd "$DOTS_CFG_ROOT" || exit 1

    local IFS='
'
    local dir_to_sync
    for dir_to_sync in $dirs_to_sync; do
        sync_dir "$DOTS_CFG_ROOT/$dir_to_sync" "$HOME_CFG_ROOT/$dir_to_sync"
    done
}


main() {
    if [ $# -lt 1 ]; then
        main_fzf
    else
        main_cli "$@"
    fi
}

main "$@"

