#! /usr/bin/env sh

find "$HOME/materiais-vetes/" -type f -print0 \
    | sort -z \
    | fzf --read0 --print0 -e -i -m +s \
    | sed -z -e "s|'|\'|g" -e 's|"|\"|g' \
    | xargs -0 -I {} sh -c "xdg-open '{}' >/dev/null 2>&1 &"

