#! /bin/sh


FZF_BIND_COMMANDS="\
ctrl-r:change-preview-window(top,75%|right,50%),\
enter:execute(echo {+} | xargs --max-args 2 man)+clear-selection,\
esc:cancel\
"

man -k . \
    | sed 's|\(\S\+\)\s\+(\(\S\+\)).\+|\2\t\t\1|' \
    | fzf \
        -i -m --exact --cycle \
        --info=inline \
        --header="Shift + Up/Down to scroll. ESC to quit." --header-first \
        --preview "man '{}'" \
        --bind="$FZF_BIND_COMMANDS" \
        --query="!^3 " # Do not show, by default, (C, CPP, etc...) functions
