#! /bin/sh


fzf_initial_query="!^3 " # Do not show, by default, (C, CPP, etc...) functions
[ -n "$1" ] && {
    fzf_initial_query="${fzf_initial_query}$1"
}

FZF_BIND_COMMANDS="\
ctrl-r:change-preview-window(top,75%|right,50%),\
enter:execute(echo {+} | xargs --max-args 2 man)+clear-selection,\
esc:cancel\
"

fzf_preview_window="right,75%,border-left"
fzf_preview_window="$fzf_preview_window,<100(up,75%,border-bottom)"

man -k . \
    | sed 's|\(\S\+\)\s\+(\(\S\+\)).\+|\2\t\t\1|' \
    | fzf \
        -i -m -e --info=inline \
        --header="Shift + Up/Down to scroll. ESC to quit." --header-first \
        --preview "man '{}'" --preview-window="$fzf_preview_window" \
        --bind="$FZF_BIND_COMMANDS" \
        --query="$fzf_initial_query"
