#! /usr/bin/env python


import fire
import sys
import os


def main(*files):
    for file in files:
        dir, base = os.path.split(path)
        name = os.path.join(dir, base.lower().replace(" ", "-"))

        if os.path.exists(name):
            print(f"'{name}' exists, skipping.", file=sys.stderr)

        os.system(f"mv {path} {lower}")


if __name__ == "__main__":
    fire.Fire(main)

