#! /usr/bin/env python


import sys
import os


if __name__ == "__main__":
    for path in sys.argv[1:]:
        dir, file = os.path.split(path)
        lower = os.path.join(dir, file.lower())
        if os.path.exists(lower):
            print(f"Path '{lower}' already exists, skipping.", file=sys.stderr)
        os.system(f"mv {path} {lower}")

