#! /bin/sh


fatal() {
    >&2 echo "$@"
    exit 1
}


[ -n "$PASSWORD_STORE_DIR" ] || fatal '$PASSWORD_STORE_DIR is not set. Quitting'
files="$(find $PASSWORD_STORE_DIR/ -name \*.gpg -printf '%P\n')"

menu_dir="$HOME/cln/semi-dmenu"
cd "$menu_dir" || fatal 'Missing menu_dir, quitting.'

choice="$(echo "$files" | python.exe menu.py)"
[ -n "$choice" ] && pass show "${choice%.*}" | { IFS= read -r pass; printf %s "$pass"; } | clip.exe

