#! /usr/bin/env sh


emoji_file="${XDG_DATA_HOME:-$HOME/.local/share}/emoji"
[ -f "$emoji_file" ] || { >&2 echo "No emoji source" && exit 1; }


chosen=$(rofi -multi-select -dmenu -i -p "Pick emojies" -input "$emoji_file")
[ -z "$chosen" ] && exit


emojies=$(echo "$chosen" | cut -d ' ' -f1 | paste -sd '')
echo -n $emojies | xsel -bi
notify-send "Copied '$emojies' into the clipboard."

