#! /bin/sh


song_name="$( \
    mpc list title \
        | shuf \
        | dmenu -i \
        | tr '\n' '\0' \
        | sed 's|"|_UNSUPPORTED_CHAR_DOUBLE_QUOTE_|g' \
)"


if mpc searchplay title "$song_name"; then
    exit 0
elif mpc findadd title "$song_name"; then
    mpc searchplay title "$song_name"
else
    notify-send -t 3000 "Song not Found!" "$song_name"
fi

