#! /bin/sh


USAGE="$0 [browser-names...]"


fatal() {
    >&2 echo "$@" && exit 1
}


if [ "$#" -lt 1 ]; then
   browsers="$BROWSER"
else
   browsers="$@"
fi


for browser in "$browsers"; do
    case "$browser" in
        -h|--help)
            fatal "$USAGE"
            ;;
        ff|firefox)
            firefox --private &
            ;;
        qb|qutebrowser)
            qutebrowser ":open -p"
            ;;
        *)
            fatal "Unsupported browser: $browser"
            ;;
    esac
done

