#! /bin/sh


USAGE="$0 [browser-names...]"


fatal() {
    >&2 echo "$@" && exit 1
}


readonly browser="${1:-$BROWSER}"
[ -z "$browser" ] && fatal "No browser supplied."


case "$browser" in
    -h|--help)
        fatal "$USAGE"
        ;;
    ff|firefox) exec firefox --private ;;
    qb|qutebrowser) exec qutebrowser ":open -p" ;;
    chrome) exec chrome --incognito ;;
    chromium) exec chromium --incognito ;;
    ungoogled-chromium) exec ungoogled-chromium --incognito ;;
    *)
        fatal "Unsupported browser: $browser"
        ;;
esac

