#! /usr/bin/sh


find "$@" -type f -print0 \
    | sort -z \
    | fzf \
        --exact -i --multi \
        --read0 --print0 \
        --info=inline --header="Open files from '$*'" \
    | xargs -r0L1 detach xdg-open

