#! /usr/bin/sh

cd "$1" || exit 1

# REMOVE_DIACRITICS="${SCRIPTS:-$HOME/scripts}/remove-diacritics"
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --trim --sort=path" 
FILENAME_FROM_ENTRY="printf '%s\n' {+} | cut -d: -f1"
BAT_AS_PAGER="bat --paging=always --style=numbers"
SNOW_RG_PAGER="${SCRIPTS:-$HOME/scripts}/snow-rg-pager.sh"

FZF_HEADER="\
${*:-"$(pwd)"}
(Shift-)Tab to (de)select
Ctrl + ([V]im | [L]ess | [O]pen | [P]rint | [Y]ank | [W]rap | [R]otate)"

FZF_BIND_COMMANDS="\
ctrl-v:become($FILENAME_FROM_ENTRY | xargs --open-tty ${EDITOR:-vim} -p),\
ctrl-l:execute(printf '%s\n' {+} | $SNOW_RG_PAGER)+clear-selection,\
ctrl-o:become($FILENAME_FROM_ENTRY | xargs --max-args=1 detach xdg-open),\
ctrl-p:become($FILENAME_FROM_ENTRY),\
ctrl-y:execute($FILENAME_FROM_ENTRY | xsel -ib),\
ctrl-w:toggle-preview-wrap,\
ctrl-r:change-preview-window(right,70%|top,60%),\
change:reload($RG_PREFIX {q} || true),\
esc:cancel,\
enter:ignore" 

FZF_PREVIEW='bat \
    --color always \
    --style="numbers" \
    --highlight-line {2}\
    {1}' 
    # --terminal-width="$FZF_PREVIEW_COLUMNS" \

FZF_DEFAULT_COMMAND="$RG_PREFIX ''" fzf \
    -i --multi \
    --ansi --delimiter=: \
    --info=inline --header-first --header="$FZF_HEADER" \
    --preview="$FZF_PREVIEW"\
    --preview-window="right,70%,wrap,+{2}/2"\
    --bind="$FZF_BIND_COMMANDS"
