#!/bin/bash


MENU="\
 Lock
 Switch User
 Logout
 Suspend
 Hybernate
 Reboot
 Shutdown"


if [ "$1" = "-d" ]; then
    MENU_CMD="dmenu\
        -fn 'Knack Nerd Font 14'\
        -p 'System'"
         
else
    MENU_CMD="rofi \
        -dmenu \
        -i \
        -p 'System' \
        -width 10 \
        -hide-scrollbar \
        -line-padding 4 \
        -padding 20 \
        -lines 4"
fi


case "$(eval "$MENU_CMD" <<< "$MENU")" in
    *Lock) i3lock-fancy ;;
    *Switch-User) dm-tool switch-to-greeter ;;
    *Logout) openbox --exit;;
    *Suspend) systemctl suspend ;;
    *Hybernate) systemctl hybernate ;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac

