#! /bin/sh


ICON_ERR=/usr/share/icons/Papirus/32x32/status/dialog-error.svg
ICON_HDD=/usr/share/icons/Papirus/32x32/devices/drive-harddisk.svg


if [ -t 1 ]; then
    in_terminal=true
fi


choose() {
    choices=$(xargs -r -I "{}" echo "{}")
    if [ "$in_terminal" = true ]; then
        echo "$choices" | fzf -e -i --prompt="$1 "
    else
        echo "$choices" | rofi -dmenu -i -p "$1"
    fi
}


if [ "$1" = "-m" ]; then
    parts=$(lsblk -lp | grep "part $" | awk '{print $1 " ("$4")"}')
    [ -z "$parts" ] && exit

    chosen=$(echo "$parts" | choose "What to mount?" | awk '{print $1}')
    [ -z "$chosen" ] && exit
    
    msg=$(udisksctl mount -b "$chosen")
    ret=$?
    echo -n $msg | sed -r "s|^Mounted $chosen at (.+)\.$|\1|" | xsel -bi

elif [ "$1" = "-u" ]; then
    parts=$(lsblk -lp | grep "part ." | awk '{print $1" ("$7")"}')
    [ -z "$parts" ] && exit

    chosen=$(echo "$parts" | choose "What to unmount?" | awk '{print $1}')
    [ -z "$chosen" ] && exit

    msg=$(udisksctl unmount -b "$chosen")
    ret=$?
    
else
    echo "Usage: usbeast < -m | -u > (mount or unmount)" && exit 1
fi


if [ ! -t 1 ]; then
    if [ $ret -eq 0 ]; then
        notify-send -t 3000 -i "$ICON_HDD" "$msg"
    else
        notify-send -t 3000 -i "$ICON_ERR" "$msg"
    fi
else
    echo "$msg"
fi
