#! /usr/bin/env sh


cd "$(mktemp -d)"
original_window="$(xdotool getwindowfocus)"

for window_id in $(wmctrl -l | awk '{print $1}'); do
    wmctrl -ia "$window_id" # I wish this line wasnt needed
    import -window "$window_id" "$window_id.png"
done

wmctrl -ia "$original_window"

for window_id in $(ls | sxiv -tio | cut -d '.' -f 1); do
    wmctrl -ia "$window_id"
done

